"""empty message

Revision ID: 0ab3df6cfe99
Revises: 2042659b8c48
Create Date: 2026-06-05 12:14:04.206028

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '0ab3df6cfe99'
down_revision = '2042659b8c48'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('package_collection', schema=None) as batch_op:
        batch_op.add_column(sa.Column('show_on_home', sa.Boolean(), nullable=True))
        batch_op.add_column(sa.Column('home_index', sa.Integer(), nullable=True))

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('package_collection', schema=None) as batch_op:
        batch_op.drop_column('home_index')
        batch_op.drop_column('show_on_home')

    # ### end Alembic commands ###
