"""empty message

Revision ID: 107cfc1b6598
Revises: 0ab3df6cfe99
Create Date: 2026-06-08 12:01:29.556439

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '107cfc1b6598'
down_revision = '0ab3df6cfe99'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('package_collection_association',
    sa.Column('package_id', sa.Integer(), nullable=False),
    sa.Column('package_collection_id', sa.Integer(), nullable=False),
    sa.ForeignKeyConstraint(['package_collection_id'], ['package_collection.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['package_id'], ['package.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('package_id', 'package_collection_id')
    )
    with op.batch_alter_table('form', schema=None) as batch_op:
        batch_op.add_column(sa.Column('enquiry_type', sa.String(length=100), nullable=True))

    with op.batch_alter_table('package', schema=None) as batch_op:
        batch_op.drop_constraint(batch_op.f('package_package_collection_id_fkey'), type_='foreignkey')
        batch_op.drop_column('package_collection_id')

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('package', schema=None) as batch_op:
        batch_op.add_column(sa.Column('package_collection_id', sa.INTEGER(), autoincrement=False, nullable=False))
        batch_op.create_foreign_key(batch_op.f('package_package_collection_id_fkey'), 'package_collection', ['package_collection_id'], ['id'], ondelete='CASCADE')

    with op.batch_alter_table('form', schema=None) as batch_op:
        batch_op.drop_column('enquiry_type')

    op.drop_table('package_collection_association')
    # ### end Alembic commands ###
