"""empty message

Revision ID: 2042659b8c48
Revises: bf798b2fabd1
Create Date: 2026-06-05 09:24:06.718830

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '2042659b8c48'
down_revision = 'bf798b2fabd1'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('form', schema=None) as batch_op:
        batch_op.drop_constraint(batch_op.f('form_package_id_fkey'), type_='foreignkey')
        batch_op.create_foreign_key(None, 'package', ['package_id'], ['id'], ondelete='CASCADE')

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('form', schema=None) as batch_op:
        batch_op.drop_constraint(None, type_='foreignkey')
        batch_op.create_foreign_key(batch_op.f('form_package_id_fkey'), 'package', ['package_id'], ['id'])

    # ### end Alembic commands ###
